@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle uml1

[Pump]
[Water Reservoir]
[Drain]

package "Feather" {
   node "GPIO Pins" {
    [D5]
    [D6]
    [D12]
   }
    node "Python program"{
       node "pumping_controller" {
       [remote_event_notifier]
       [pump_controller]
       [water_level]
       }
    }
  [pump_controller] -up-> [D12]:Programmatic\nOn/Off
  [water_level] -up-> [D5]:Programmatic\n"Wet"/"Dry"
  [water_level] -up-> [D6]:Programmatic\n"Wet"/"Dry"
}

package "Spring Boot\nRest Server" {
  [SpringBoot Java Application]
}


database "Physical Switch/Sensors" {
   [D12]--> [Relay Switch]:Wired
   [Relay Switch]--> [Pump]:Wired
   [Top Water Sensor] --> [D6]:Wired
   [Bottom Water Sensor]--> [D5]:Wired
}
[remote_event_notifier] --down-> [SpringBoot Java Application]:HTTP POST/GET
[Top Water Sensor] --down-> [Water Reservoir]:Inside
[Bottom Water Sensor] --down-> [Water Reservoir]:Inside
[Water Reservoir] --down-> [Pump]:Tubing
[Pump] ---> [Drain]:Tubing
@enduml